ADDRESS: 'Update soon'
ADMIN_DATE_FORMAT: 'd F, Y'
ADMIN_DATE_TIME_FORMAT: 'd F, Y H:i A'
ADMIN_EMAIL: dawid@uupro.com
ADMIN_PAGE_LIMIT: '20'
CONTACT_US_TEXT: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
DEFAULT_BANNER: '1'
DEFAULT_CURRENCY: USD
DEVELOPMENT_MODE: '0'
FROM_EMAIL: contact@collabthem.com
FRONT_DATE_FORMAT: 'd F, Y'
FRONT_DATE_TIME_FORMAT: 'd F, Y'
FRONT_PAGE_LIMIT: '12'
GOOGLE_MAP_KEY: AIzaSyD9pg6_fzfgDHJFSW0wkrIcuCOw_V9qOfM
MAIN_FAVICON: uploads/dots-.png
MAIN_LOGO: uploads/logo_.png
RESET_URL_EXPIRED: '24'
SMTP_ALLOW: '1'
SMTP_EMAIL_HOST: mail.collabthem.com
SMTP_PASSWORD: collabthem@123
SMTP_PORT: '587'
SMTP_TLS: '0'
SMTP_USERNAME: support@collabthem.com
SOCIAL_LINKS: '[{"icon":"fab fa-facebook-f","url":"https:\/\/www.facebook.com\/collabthem","title":"Facebook"},{"icon":"fab fa-instagram","url":"https:\/\/www.instagram.com\/collabthem","title":"instagram"},{"icon":"fab fa-twitter","url":"https:\/\/twitter.com\/collabthem","title":"twitter"}]'
SYSTEM_APPLICATION_NAME: Collabthem
TELEPHONE: +91-1234567890
WEBSITE_OWNER: 'Dawid Mazurkiewicz'
